### ISSUE TITLE
How to get it run

### ISSUE THREAD

**Issue by toble** [Gurkenschreck/Gurkenplayer#1]
Hi, 
I've discovered your project yesterday and since then tried to run it. At first I had some issues (map not loading) but then managed to find out why. 
The problem was the missing Lidgren.Network.dll file which I had to copy into the mod folder where the Gurkenplayer.dll is automatically placed by your build script. After that I managed to run it, but had no time to test anything yet.

Would be nice if you mentioned this in the readme or an installation file.

Kind regards 
toble

**Comment by Gurkenschreck** [comment]
Hello toble,
thanks for your feedback! I updated the readme.md with an installation guide, you can check that out.
Maybe I can even include the Lidgren.Network.dll into the build script, should not be too hard...

Greetings,
Gurkenschreck

**Comment by toble** [comment]
Great thank you. I will keep watching and try it out from time to time.
